// <auto-generated />
using System;
using Infraesctructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraesctructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Domain.Entities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("cartId");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("clientId");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("CartId");

                    b.HasIndex("ClientId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("clientId");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<int>("DNI")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("dni");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("lastName");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("phoneNumber");

                    b.HasKey("ClientId");

                    b.ToTable("Client", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Address = "Bynnon 2331",
                            DNI = 23344312,
                            FirstName = "Nicolas",
                            LastName = "Vitek",
                            PhoneNumber = "4234-1231"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("orderId");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cartId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<double>("Total")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total");

                    b.HasKey("OrderId");

                    b.HasIndex("CartId")
                        .IsUnique();

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("productId");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("brand");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("price");

                    b.HasKey("ProductId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "Sol Serrano",
                            Code = "a-043",
                            Description = "40 grm",
                            Image = "Http://static.cotodigital3.com.ar/sitios/fotos/full/00523500/00523588.jpg?3.0.138f",
                            Name = "Alfajor",
                            Price = 37.990000000000002
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "Amanda",
                            Code = "a-099",
                            Description = "Edicion 1950, 1 kgrm",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00510600/00510606.jpg?3.0.138f",
                            Name = "Yerba mate",
                            Price = 543.33000000000004
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "Corper",
                            Code = "a-007",
                            Description = "520 grm",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00263300/00263369.jpg?3.0.138f",
                            Name = "Pure de tomate",
                            Price = 95.400000000000006
                        },
                        new
                        {
                            ProductId = 4,
                            Brand = "La Virginia",
                            Code = "a-211",
                            Description = "20 grm",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00230100/00230124.jpg?3.0.138f",
                            Name = "Cafe molido",
                            Price = 388.14999999999998
                        },
                        new
                        {
                            ProductId = 5,
                            Brand = "Doña Pupa",
                            Code = "a-055",
                            Description = "Bajo en sodio, 340 grm",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00537400/00537472.jpg?3.0.138f",
                            Name = "Arvejas",
                            Price = 65.390000000000001
                        },
                        new
                        {
                            ProductId = 6,
                            Brand = "Bonaqua",
                            Code = "b-013",
                            Description = "Sin gas, 2.5 lt",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00289600/00289636.jpg?3.0.138f",
                            Name = "Agua mineral",
                            Price = 91.709999999999994
                        },
                        new
                        {
                            ProductId = 7,
                            Brand = "Coca-Cola",
                            Code = "b-020",
                            Description = "Light, 2 lt",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00189500/00189594.jpg?3.0.138f",
                            Name = "Gaseosa",
                            Price = 134.55000000000001
                        },
                        new
                        {
                            ProductId = 8,
                            Brand = "La Serenisima",
                            Code = "f-103",
                            Description = "Entera, sache 1 lt",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00170500/00170599.jpg?3.0.138f",
                            Name = "Leche",
                            Price = 183.25
                        },
                        new
                        {
                            ProductId = 9,
                            Brand = "Fudy",
                            Code = "c-017",
                            Description = "Caja 160 grm",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00499100/00499140.jpg?3.0.138f",
                            Name = "Cookie Sandwich",
                            Price = 259.0
                        },
                        new
                        {
                            ProductId = 10,
                            Brand = "Elite",
                            Code = "l-022",
                            Description = "Doble hoja, caja 100u",
                            Image = "https://static.cotodigital3.com.ar/sitios/fotos/full/00264600/00264677.jpg?3.0.138f",
                            Name = "Pañuelos",
                            Price = 149.87
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProductCart", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cartId");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("productId");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.HasKey("CartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCart", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Cart", b =>
                {
                    b.HasOne("Domain.Entities.Client", "Client")
                        .WithMany("Cart")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.Cart", "Cart")
                        .WithOne("Order")
                        .HasForeignKey("Domain.Entities.Order", "CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Domain.Entities.ProductCart", b =>
                {
                    b.HasOne("Domain.Entities.Cart", "Cart")
                        .WithMany("ProductCart")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("ProductCart")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Cart", b =>
                {
                    b.Navigation("Order");

                    b.Navigation("ProductCart");
                });

            modelBuilder.Entity("Domain.Entities.Client", b =>
                {
                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductCart");
                });
#pragma warning restore 612, 618
        }
    }
}
