services:
  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - API_KEY=${API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/data/mydatabase.db?busy_timeout=5000
    volumes:
      - ./Backend/data:/data
    restart: unless-stopped

  frontend:
    build: ./Frontend
    ports:
      - "5500:80"
    depends_on:
      - backend
    restart: unless-stopped